import AboutMe from "./about/aboutMe";
import Introduction from "./introduction/introduction";
import Experience from "./experience/experience";
import SectionHeader from "./sectionHeader/sectionHeader";
import PortfolioSection from "./portfolio/portfolioSection/portfolioSection";
import GithubSilhouette from "./helpers/githubSVG";
import GithubOutline from "./helpers/githubOutline";
import FolderIcon from "./helpers/folderIcon";
import PortfolioCard from "./portfolio/portfolioCard/portfolioCard";
import Header from "./header/header";
import Logo from "./helpers/logo";

export const AboutMeComponent = AboutMe;
export const IntroductionComponent = Introduction;
export const ExperienceComponent = Experience;
export const SectionHeaderComponent = SectionHeader;
export const PortfolioSectionComponent = PortfolioSection;
export const GithubSVGComponent = GithubSilhouette;
export const GithubSVGOutlineComponent = GithubOutline;
export const FolderIconComponent = FolderIcon;
export const PortfolioCardComponent = PortfolioCard;
export const HeaderComponent = Header;
export const LogoComponent = Logo;
